//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import (
	"github.com/google/uuid"
	"time"
)

type BankAccountTransactionImportRun struct {
	BankAccountImportRunID uuid.UUID `sql:"primary_key"`
	BankAccountID          uuid.UUID
	ImportRunID            uuid.UUID
	Status                 ImportRunStatus
	CreatedAt              time.Time
}
