//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import (
	"github.com/google/uuid"
	"time"
)

type BrokerageAccountTransaction struct {
	BrokerageAccountTransactionID uuid.UUID `sql:"primary_key"`
	ExternalTransactionID         *string
	ImportRunID                   uuid.UUID
	SymbolOrCusip                 *string
	Price                         *float64
	Quantity                      *float64
	Amount                        *float64
	Side                          *Side
	TransactionDate               *time.Time
	Description                   *string
}
