//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import (
	"github.com/google/uuid"
	"time"
)

type BrokerageAccountOpenLotVersion struct {
	BrokerageAccountOpenLotVersionID uuid.UUID `sql:"primary_key"`
	BrokerageAccountOpenLotID        uuid.UUID
	VersionDate                      time.Time
	ImportRunID                      uuid.UUID
	TotalCostBasis                   *float64
	Quantity                         *float64
	CreatedAt                        time.Time
}
