//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import (
	"github.com/google/uuid"
	"time"
)

type CurrentBrokerageAccountOpenLot struct {
	BrokerageAccountOpenLotID *uuid.UUID
	BrokerageAccountID        *uuid.UUID
	SymbolOrCusip             *string
	LotCreationDate           *time.Time
	ImportRunID               *uuid.UUID
	VersionDate               *time.Time
	TotalCostBasis            *float64
	Quantity                  *float64
}
