//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import (
	"github.com/google/uuid"
	"time"
)

type UploadedFile struct {
	UploadedFileID   uuid.UUID `sql:"primary_key"`
	UploadedByUserID uuid.UUID
	FileName         string
	S3Bucket         string
	S3FilePath       string
	FileSizeKb       int32
	CreatedAt        time.Time
}
