//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package enum

import "github.com/go-jet/jet/v2/postgres"

var ImportRunStatus = &struct {
	Pending   postgres.StringExpression
	Running   postgres.StringExpression
	Completed postgres.StringExpression
	Failed    postgres.StringExpression
}{
	Pending:   postgres.NewEnumValue("pending"),
	Running:   postgres.NewEnumValue("running"),
	Completed: postgres.NewEnumValue("completed"),
	Failed:    postgres.NewEnumValue("failed"),
}
