//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/postgres"
)

var ImportRunStatus = newImportRunStatusTable("public", "import_run_status", "")

type importRunStatusTable struct {
	postgres.Table

	//Columns
	ImportRunStatusID postgres.ColumnString
	ImportRunID       postgres.ColumnString
	CreatedAt         postgres.ColumnTimestampz
	UpdatedAt         postgres.ColumnTimestampz
	Status            postgres.ColumnString
	Description       postgres.ColumnString

	AllColumns     postgres.ColumnList
	MutableColumns postgres.ColumnList
}

type ImportRunStatusTable struct {
	importRunStatusTable

	EXCLUDED importRunStatusTable
}

// AS creates new ImportRunStatusTable with assigned alias
func (a ImportRunStatusTable) AS(alias string) *ImportRunStatusTable {
	return newImportRunStatusTable(a.SchemaName(), a.TableName(), alias)
}

// Schema creates new ImportRunStatusTable with assigned schema name
func (a ImportRunStatusTable) FromSchema(schemaName string) *ImportRunStatusTable {
	return newImportRunStatusTable(schemaName, a.TableName(), a.Alias())
}

func newImportRunStatusTable(schemaName, tableName, alias string) *ImportRunStatusTable {
	return &ImportRunStatusTable{
		importRunStatusTable: newImportRunStatusTableImpl(schemaName, tableName, alias),
		EXCLUDED:             newImportRunStatusTableImpl("", "excluded", ""),
	}
}

func newImportRunStatusTableImpl(schemaName, tableName, alias string) importRunStatusTable {
	var (
		ImportRunStatusIDColumn = postgres.StringColumn("import_run_status_id")
		ImportRunIDColumn       = postgres.StringColumn("import_run_id")
		CreatedAtColumn         = postgres.TimestampzColumn("created_at")
		UpdatedAtColumn         = postgres.TimestampzColumn("updated_at")
		StatusColumn            = postgres.StringColumn("status")
		DescriptionColumn       = postgres.StringColumn("description")
		allColumns              = postgres.ColumnList{ImportRunStatusIDColumn, ImportRunIDColumn, CreatedAtColumn, UpdatedAtColumn, StatusColumn, DescriptionColumn}
		mutableColumns          = postgres.ColumnList{ImportRunIDColumn, CreatedAtColumn, UpdatedAtColumn, StatusColumn, DescriptionColumn}
	)

	return importRunStatusTable{
		Table: postgres.NewTable(schemaName, tableName, alias, allColumns...),

		//Columns
		ImportRunStatusID: ImportRunStatusIDColumn,
		ImportRunID:       ImportRunIDColumn,
		CreatedAt:         CreatedAtColumn,
		UpdatedAt:         UpdatedAtColumn,
		Status:            StatusColumn,
		Description:       DescriptionColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
	}
}
